version: 2
build:
  os: "ubuntu-24.04"
  tools:
    python: "3"
  apt_packages:
    # rsvg-convert for SVG -> PDF conversion
    # using Sphinx extension sphinxcontrib.rsvgconverter, see
    # https://github.com/missinglinkelectronics/sphinxcontrib-svg2pdfconverter
    - librsvg2-bin
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    install:
      - pip install --upgrade pip
      - pip install --group doc .
      # fallback theme:
      - pip install insipid-sphinx-theme
sphinx:
  configuration: doc/conf.py
formats: all
